Name:           ros-kinetic-object-recognition-ros
Version:        0.3.7
Release:        0%{?dist}
Summary:        ROS object_recognition_ros package

Group:          Development/Libraries
License:        BSD
URL:            wg-perception.github.io/object_recognition_ros
Source0:        %{name}-%{version}.tar.gz

Requires:       boost-devel
Requires:       ros-kinetic-actionlib
Requires:       ros-kinetic-ecto
Requires:       ros-kinetic-ecto-image-pipeline
Requires:       ros-kinetic-ecto-ros
Requires:       ros-kinetic-geometric-shapes
Requires:       ros-kinetic-object-recognition-core
Requires:       ros-kinetic-object-recognition-msgs
Requires:       ros-kinetic-pluginlib
Requires:       ros-kinetic-rostopic
BuildRequires:  boost-devel
BuildRequires:  ros-kinetic-actionlib
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-cmake-modules
BuildRequires:  ros-kinetic-ecto
BuildRequires:  ros-kinetic-ecto-image-pipeline
BuildRequires:  ros-kinetic-ecto-ros
BuildRequires:  ros-kinetic-geometric-shapes
BuildRequires:  ros-kinetic-object-recognition-core
BuildRequires:  ros-kinetic-object-recognition-msgs
BuildRequires:  ros-kinetic-pluginlib
BuildRequires:  ros-kinetic-rostest
BuildRequires:  ros-kinetic-visualization-msgs

%description
object_recognition_core contains tools to launch several recognition pipelines,
train objects, store models ...

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Sat Aug 27 2016 Vincent Rabaud <vincent.rabaud@gmail.com> - 0.3.7-0
- Autogenerated by Bloom

* Sat Aug 27 2016 Vincent Rabaud <vincent.rabaud@gmail.com> - 0.3.6-0
- Autogenerated by Bloom

* Sun Apr 24 2016 Vincent Rabaud <vincent.rabaud@gmail.com> - 0.3.5-0
- Autogenerated by Bloom

